name: "Continuous Integration"

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  tests:
    name: "Tests (Unit and Feature tests)"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.0']

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2

    - name: "Setup PHP with extensions"
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, mysqlnd, pdo_mysql, intl, gd, exif, imagick
        tools: composer:v2
        coverage: none

    - name: "Cache dependencies installed with composer"
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: dependencies-php-${{ matrix.php-versions }}-composer-${{ hashFiles('composer.json') }}

    - name: "Shutdown the Default MySQL"
      run: sudo service mysql stop

    - name: "Set up MariaDB"
      uses: getong/mariadb-action@v1.1
      with:
        mysql database: 'testing'
        mysql user: 'homestead'
        mysql password: 'secret'

    - name: "Copy .env"
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: "Install Dependencies"
      run: composer install --no-interaction --no-progress --no-suggest

    - name: "Generate key"
      run: php artisan key:generate

    - name: "Directory Permissions"
      run: chmod -R 777 storage bootstrap/cache

    - name: "Execute tests (Unit and Feature tests)"
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: testing
        DB_USERNAME: homestead
        DB_PASSWORD: secret
      run: vendor/bin/pest --stop-on-failure
